version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: showroom-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: showroom_db
    ports:
      - "5432:5432"
    volumes:
      - showrooms_data:/var/lib/postgresql/data

volumes:
  showrooms_data: